const insertData = require("./conexion.js");

const pacientes = [
  {
    idPaciente: "P1",
    nombre: "Juan",
    edad: 10,
    sexo: "M",
    idCiudad: "C7",
    idEtapaVida: "EV2",
  },
  {
    idPaciente: "P2",
    nombre: "María",
    edad: 30,
    sexo: "F",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P3",
    nombre: "Pedro",
    edad: 18,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P4",
    nombre: "Ana",
    edad: 8,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P5",
    nombre: "Luis",
    edad: 45,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P6",
    nombre: "Laura",
    edad: 32,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P7",
    nombre: "Carlos",
    edad: 55,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P8",
    nombre: "Marta",
    edad: 28,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P9",
    nombre: "David",
    edad: 22,
    sexo: "M",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P10",
    nombre: "Isabel",
    edad: 50,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P11",
    nombre: "Cristina",
    edad: 37,
    sexo: "F",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P12",
    nombre: "Sergio",
    edad: 33,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P13",
    nombre: "Beatriz",
    edad: 29,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P14",
    nombre: "Gabriel",
    edad: 42,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P15",
    nombre: "Natalia",
    edad: 26,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P16",
    nombre: "Diego",
    edad: 31,
    sexo: "M",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },

  {
    idPaciente: "P17",
    nombre: "Elena",
    edad: 28,
    sexo: "F",
    idCiudad: "C5",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P18",
    nombre: "Javier",
    edad: 19,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P19",
    nombre: "Sofía",
    edad: 55,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P20",
    nombre: "Andrés",
    edad: 42,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P21",
    nombre: "Lorena",
    edad: 26,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P22",
    nombre: "Carlos",
    edad: 31,
    sexo: "M",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P23",
    nombre: "Patricia",
    edad: 45,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P24",
    nombre: "Raúl",
    edad: 33,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P25",
    nombre: "Mónica",
    edad: 29,
    sexo: "F",
    idCiudad: "C3",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P26",
    nombre: "Alejandro",
    edad: 50,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P27",
    nombre: "Laura",
    edad: 40,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P28",
    nombre: "Manuel",
    edad: 60,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P29",
    nombre: "Eva",
    edad: 27,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P30",
    nombre: "Roberto",
    edad: 48,
    sexo: "M",
    idCiudad: "C1",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P31",
    nombre: "Luisa",
    edad: 23,
    sexo: "F",
    idCiudad: "C15",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P32",
    nombre: "Fernando",
    edad: 37,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P33",
    nombre: "Lucía",
    edad: 15,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P34",
    nombre: "Gonzalo",
    edad: 40,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P35",
    nombre: "Camila",
    edad: 31,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P36",
    nombre: "José",
    edad: 27,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P37",
    nombre: "Carolina",
    edad: 35,
    sexo: "F",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P38",
    nombre: "Ángel",
    edad: 23,
    sexo: "M",
    idCiudad: "C7",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P39",
    nombre: "Isabella",
    edad: 7,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P40",
    nombre: "Antonio",
    edad: 58,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P41",
    nombre: "Daniela",
    edad: 21,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P42",
    nombre: "Ricardo",
    edad: 47,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P43",
    nombre: "Susana",
    edad: 66,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P44",
    nombre: "Samuel",
    edad: 40,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P45",
    nombre: "Valentina",
    edad: 16,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P46",
    nombre: "Alberto",
    edad: 51,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P47",
    nombre: "Gloria",
    edad: 61,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P48",
    nombre: "Pablo",
    edad: 36,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P49",
    nombre: "Cecilia",
    edad: 33,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P50",
    nombre: "Jorge",
    edad: 29,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV3",
  },

  {
    idPaciente: "P51",
    nombre: "Valeria",
    edad: 24,
    sexo: "F",
    idCiudad: "C3",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P52",
    nombre: "Eduardo",
    edad: 49,
    sexo: "M",
    idCiudad: "C7",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P53",
    nombre: "Susana",
    edad: 61,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P54",
    nombre: "Gabriel",
    edad: 28,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P55",
    nombre: "Marta",
    edad: 34,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P56",
    nombre: "Raúl",
    edad: 55,
    sexo: "M",
    idCiudad: "C12",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P57",
    nombre: "Laura",
    edad: 19,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV2",
  },
  {
    idPaciente: "P58",
    nombre: "David",
    edad: 42,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P59",
    nombre: "Carolina",
    edad: 30,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P60",
    nombre: "José",
    edad: 37,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P61",
    nombre: "Sofía",
    edad: 13,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P62",
    nombre: "Andrés",
    edad: 52,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P63",
    nombre: "Luisa",
    edad: 22,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P64",
    nombre: "Pablo",
    edad: 29,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P65",
    nombre: "Elena",
    edad: 26,
    sexo: "F",
    idCiudad: "C15",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P66",
    nombre: "Carlos",
    edad: 47,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P67",
    nombre: "Valentina",
    edad: 18,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P68",
    nombre: "Javier",
    edad: 38,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P69",
    nombre: "Cecilia",
    edad: 29,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P70",
    nombre: "Fernando",
    edad: 41,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P71",
    nombre: "Mónica",
    edad: 34,
    sexo: "F",
    idCiudad: "C5",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P72",
    nombre: "Diego",
    edad: 23,
    sexo: "M",
    idCiudad: "C1",
    idEtapaVida: "EV2",
  },
  {
    idPaciente: "P73",
    nombre: "Lorena",
    edad: 31,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P74",
    nombre: "Roberto",
    edad: 57,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P75",
    nombre: "Natalia",
    edad: 25,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P76",
    nombre: "Gonzalo",
    edad: 43,
    sexo: "M",
    idCiudad: "C8",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P77",
    nombre: "Patricia",
    edad: 39,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P78",
    nombre: "Manuel",
    edad: 62,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P79",
    nombre: "Camila",
    edad: 20,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P80",
    nombre: "Eva",
    edad: 33,
    sexo: "F",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P81",
    nombre: "Alberto",
    edad: 48,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P82",
    nombre: "Lucía",
    edad: 14,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P83",
    nombre: "Sergio",
    edad: 30,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P84",
    nombre: "Isabella",
    edad: 10,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P85",
    nombre: "Ángel",
    edad: 56,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P86",
    nombre: "Carolina",
    edad: 31,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P87",
    nombre: "Javier",
    edad: 27,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P88",
    nombre: "Sofía",
    edad: 51,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P89",
    nombre: "Andrés",
    edad: 37,
    sexo: "M",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P90",
    nombre: "Luisa",
    edad: 23,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P91",
    nombre: "Pablo",
    edad: 29,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P92",
    nombre: "Elena",
    edad: 32,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P93",
    nombre: "Carlos",
    edad: 45,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P94",
    nombre: "Valentina",
    edad: 17,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P95",
    nombre: "Jorge",
    edad: 41,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P96",
    nombre: "Cecilia",
    edad: 33,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P97",
    nombre: "Fernando",
    edad: 29,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P98",
    nombre: "Mónica",
    edad: 45,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P99",
    nombre: "Diego",
    edad: 30,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P100",
    nombre: "Lorena",
    edad: 24,
    sexo: "F",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P101",
    nombre: "Javier",
    edad: 39,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P102",
    nombre: "Sofía",
    edad: 52,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P103",
    nombre: "Andrés",
    edad: 29,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P104",
    nombre: "Luisa",
    edad: 33,
    sexo: "F",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P105",
    nombre: "Pablo",
    edad: 57,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P106",
    nombre: "Elena",
    edad: 28,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P107",
    nombre: "Carlos",
    edad: 46,
    sexo: "M",
    idCiudad: "C1",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P108",
    nombre: "Valentina",
    edad: 19,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P109",
    nombre: "Jorge",
    edad: 33,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P110",
    nombre: "Cecilia",
    edad: 42,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P111",
    nombre: "Fernando",
    edad: 31,
    sexo: "M",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P112",
    nombre: "Mónica",
    edad: 39,
    sexo: "F",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P113",
    nombre: "Diego",
    edad: 24,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P114",
    nombre: "Lorena",
    edad: 28,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P115",
    nombre: "Roberto",
    edad: 55,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P116",
    nombre: "Natalia",
    edad: 27,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P117",
    nombre: "Gonzalo",
    edad: 44,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P118",
    nombre: "Patricia",
    edad: 35,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P119",
    nombre: "Manuel",
    edad: 59,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P120",
    nombre: "Camila",
    edad: 21,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P121",
    nombre: "Eva",
    edad: 32,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P122",
    nombre: "Alberto",
    edad: 49,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P123",
    nombre: "Lucía",
    edad: 15,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P124",
    nombre: "Sergio",
    edad: 29,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P125",
    nombre: "Isabella",
    edad: 9,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P126",
    nombre: "Ángel",
    edad: 57,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P127",
    nombre: "Carolina",
    edad: 32,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P128",
    nombre: "Javier",
    edad: 28,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P129",
    nombre: "Sofía",
    edad: 50,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P130",
    nombre: "Andrés",
    edad: 36,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P131",
    nombre: "Luisa",
    edad: 25,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P132",
    nombre: "Pablo",
    edad: 30,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P133",
    nombre: "Elena",
    edad: 33,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P134",
    nombre: "Carlos",
    edad: 48,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P135",
    nombre: "Valentina",
    edad: 20,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P136",
    nombre: "Jorge",
    edad: 34,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P137",
    nombre: "Cecilia",
    edad: 30,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P138",
    nombre: "Fernando",
    edad: 32,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P139",
    nombre: "Mónica",
    edad: 42,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P140",
    nombre: "Diego",
    edad: 26,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P141",
    nombre: "Lorena",
    edad: 32,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P142",
    nombre: "Roberto",
    edad: 56,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P143",
    nombre: "Natalia",
    edad: 29,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P144",
    nombre: "Gonzalo",
    edad: 47,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P145",
    nombre: "Patricia",
    edad: 34,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P146",
    nombre: "Manuel",
    edad: 60,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P147",
    nombre: "Camila",
    edad: 22,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P148",
    nombre: "Eva",
    edad: 31,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P149",
    nombre: "Alberto",
    edad: 47,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P150",
    nombre: "Lucía",
    edad: 16,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P151",
    nombre: "Sergio",
    edad: 27,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P152",
    nombre: "Isabella",
    edad: 8,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P153",
    nombre: "Ángel",
    edad: 58,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P154",
    nombre: "Carolina",
    edad: 30,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P155",
    nombre: "Javier",
    edad: 29,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P156",
    nombre: "Sofía",
    edad: 53,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P157",
    nombre: "Andrés",
    edad: 37,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P158",
    nombre: "Luisa",
    edad: 26,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P159",
    nombre: "Pablo",
    edad: 31,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P160",
    nombre: "Elena",
    edad: 34,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P161",
    nombre: "Carlos",
    edad: 49,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P162",
    nombre: "Valentina",
    edad: 21,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P163",
    nombre: "Jorge",
    edad: 35,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P164",
    nombre: "Cecilia",
    edad: 31,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P165",
    nombre: "Fernando",
    edad: 33,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P166",
    nombre: "Mónica",
    edad: 43,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P167",
    nombre: "Diego",
    edad: 27,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P168",
    nombre: "Lorena",
    edad: 33,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P169",
    nombre: "Roberto",
    edad: 58,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P170",
    nombre: "Natalia",
    edad: 30,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P171",
    nombre: "Gonzalo",
    edad: 45,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P172",
    nombre: "Patricia",
    edad: 37,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P173",
    nombre: "Manuel",
    edad: 61,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P174",
    nombre: "Camila",
    edad: 23,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P175",
    nombre: "Eva",
    edad: 30,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P176",
    nombre: "Alberto",
    edad: 50,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P177",
    nombre: "Lucía",
    edad: 17,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P178",
    nombre: "Sergio",
    edad: 31,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P179",
    nombre: "Isabella",
    edad: 7,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P180",
    nombre: "Ángel",
    edad: 59,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P181",
    nombre: "Carolina",
    edad: 29,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P182",
    nombre: "Javier",
    edad: 30,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P183",
    nombre: "Sofía",
    edad: 54,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P184",
    nombre: "Andrés",
    edad: 38,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P185",
    nombre: "Luisa",
    edad: 27,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P186",
    nombre: "Pablo",
    edad: 32,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P187",
    nombre: "Elena",
    edad: 35,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P188",
    nombre: "Carlos",
    edad: 50,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P189",
    nombre: "Valentina",
    edad: 22,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P190",
    nombre: "Jorge",
    edad: 36,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P191",
    nombre: "Cecilia",
    edad: 32,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P192",
    nombre: "Fernando",
    edad: 34,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P193",
    nombre: "Mónica",
    edad: 44,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P194",
    nombre: "Diego",
    edad: 28,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P195",
    nombre: "Lorena",
    edad: 34,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P196",
    nombre: "Roberto",
    edad: 59,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P197",
    nombre: "Natalia",
    edad: 31,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P198",
    nombre: "Gonzalo",
    edad: 46,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P199",
    nombre: "Patricia",
    edad: 36,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P200",
    nombre: "Manuel",
    edad: 62,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P201",
    nombre: "Camila",
    edad: 24,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P202",
    nombre: "Eva",
    edad: 29,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P203",
    nombre: "Alberto",
    edad: 51,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P204",
    nombre: "Lucía",
    edad: 18,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P205",
    nombre: "Sergio",
    edad: 32,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P206",
    nombre: "Isabella",
    edad: 6,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P207",
    nombre: "Ángel",
    edad: 60,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P208",
    nombre: "Carolina",
    edad: 28,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P209",
    nombre: "Javier",
    edad: 31,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P210",
    nombre: "Sofía",
    edad: 55,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P211",
    nombre: "Andrés",
    edad: 39,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P212",
    nombre: "Luisa",
    edad: 28,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P213",
    nombre: "Pablo",
    edad: 33,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P214",
    nombre: "Elena",
    edad: 36,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P215",
    nombre: "Carlos",
    edad: 51,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P216",
    nombre: "Valentina",
    edad: 23,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P217",
    nombre: "Jorge",
    edad: 37,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P218",
    nombre: "Cecilia",
    edad: 33,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P219",
    nombre: "Fernando",
    edad: 35,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P220",
    nombre: "Mónica",
    edad: 45,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P221",
    nombre: "Diego",
    edad: 29,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P222",
    nombre: "Lorena",
    edad: 35,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P223",
    nombre: "Roberto",
    edad: 60,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P224",
    nombre: "Natalia",
    edad: 32,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P225",
    nombre: "Gonzalo",
    edad: 47,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P226",
    nombre: "Patricia",
    edad: 38,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P227",
    nombre: "Manuel",
    edad: 63,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P228",
    nombre: "Camila",
    edad: 25,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P229",
    nombre: "Eva",
    edad: 32,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P230",
    nombre: "Alberto",
    edad: 52,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P231",
    nombre: "Lucía",
    edad: 19,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P232",
    nombre: "Sergio",
    edad: 33,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P233",
    nombre: "Isabella",
    edad: 5,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P234",
    nombre: "Ángel",
    edad: 61,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P235",
    nombre: "Carolina",
    edad: 31,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P236",
    nombre: "Javier",
    edad: 32,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P237",
    nombre: "Sofía",
    edad: 56,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P238",
    nombre: "Andrés",
    edad: 40,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P239",
    nombre: "Luisa",
    edad: 29,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P240",
    nombre: "Pablo",
    edad: 34,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P241",
    nombre: "Elena",
    edad: 37,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P242",
    nombre: "Carlos",
    edad: 52,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P243",
    nombre: "Valentina",
    edad: 24,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P244",
    nombre: "Jorge",
    edad: 38,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P245",
    nombre: "Cecilia",
    edad: 34,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P246",
    nombre: "Fernando",
    edad: 36,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P247",
    nombre: "Mónica",
    edad: 46,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P248",
    nombre: "Diego",
    edad: 30,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P249",
    nombre: "Lorena",
    edad: 36,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P250",
    nombre: "Roberto",
    edad: 61,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },

  {
    idPaciente: "P251",
    nombre: "Natalia",
    edad: 33,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P252",
    nombre: "Gonzalo",
    edad: 48,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P253",
    nombre: "Patricia",
    edad: 39,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P254",
    nombre: "Manuel",
    edad: 64,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P255",
    nombre: "Camila",
    edad: 26,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P256",
    nombre: "Eva",
    edad: 33,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P257",
    nombre: "Alberto",
    edad: 53,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P258",
    nombre: "Lucía",
    edad: 20,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P259",
    nombre: "Sergio",
    edad: 34,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P260",
    nombre: "Isabella",
    edad: 4,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P261",
    nombre: "Ángel",
    edad: 62,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P262",
    nombre: "Carolina",
    edad: 32,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P263",
    nombre: "Javier",
    edad: 33,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P264",
    nombre: "Sofía",
    edad: 57,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P265",
    nombre: "Andrés",
    edad: 41,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P266",
    nombre: "Luisa",
    edad: 30,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P267",
    nombre: "Pablo",
    edad: 35,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P268",
    nombre: "Elena",
    edad: 38,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P269",
    nombre: "Carlos",
    edad: 53,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P270",
    nombre: "Valentina",
    edad: 25,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P271",
    nombre: "Jorge",
    edad: 39,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P272",
    nombre: "Cecilia",
    edad: 35,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P273",
    nombre: "Fernando",
    edad: 37,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P274",
    nombre: "Mónica",
    edad: 47,
    sexo: "F",
    idCiudad: "C14",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P275",
    nombre: "Diego",
    edad: 31,
    sexo: "M",
    idCiudad: "C2",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P276",
    nombre: "Lorena",
    edad: 37,
    sexo: "F",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P277",
    nombre: "Roberto",
    edad: 62,
    sexo: "M",
    idCiudad: "C9",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P278",
    nombre: "Natalia",
    edad: 34,
    sexo: "F",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P279",
    nombre: "Gonzalo",
    edad: 49,
    sexo: "M",
    idCiudad: "C11",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P280",
    nombre: "Patricia",
    edad: 40,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P281",
    nombre: "Manuel",
    edad: 65,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P282",
    nombre: "Camila",
    edad: 27,
    sexo: "F",
    idCiudad: "C10",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P283",
    nombre: "Eva",
    edad: 34,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P284",
    nombre: "Alberto",
    edad: 54,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P285",
    nombre: "Lucía",
    edad: 21,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P286",
    nombre: "Sergio",
    edad: 35,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P287",
    nombre: "Isabella",
    edad: 3,
    sexo: "F",
    idCiudad: "C1",
    idEtapaVida: "EV1",
  },
  {
    idPaciente: "P288",
    nombre: "Ángel",
    edad: 63,
    sexo: "M",
    idCiudad: "C10",
    idEtapaVida: "EV6",
  },
  {
    idPaciente: "P289",
    nombre: "Carolina",
    edad: 33,
    sexo: "F",
    idCiudad: "C8",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P290",
    nombre: "Javier",
    edad: 34,
    sexo: "M",
    idCiudad: "C6",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P291",
    nombre: "Sofía",
    edad: 58,
    sexo: "F",
    idCiudad: "C2",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P292",
    nombre: "Andrés",
    edad: 42,
    sexo: "M",
    idCiudad: "C13",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P293",
    nombre: "Luisa",
    edad: 31,
    sexo: "F",
    idCiudad: "C11",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P294",
    nombre: "Pablo",
    edad: 36,
    sexo: "M",
    idCiudad: "C5",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P295",
    nombre: "Elena",
    edad: 39,
    sexo: "F",
    idCiudad: "C9",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P296",
    nombre: "Carlos",
    edad: 54,
    sexo: "M",
    idCiudad: "C4",
    idEtapaVida: "EV5",
  },
  {
    idPaciente: "P297",
    nombre: "Valentina",
    edad: 26,
    sexo: "F",
    idCiudad: "C7",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P298",
    nombre: "Jorge",
    edad: 40,
    sexo: "M",
    idCiudad: "C3",
    idEtapaVida: "EV4",
  },
  {
    idPaciente: "P299",
    nombre: "Cecilia",
    edad: 36,
    sexo: "F",
    idCiudad: "C12",
    idEtapaVida: "EV3",
  },
  {
    idPaciente: "P300",
    nombre: "Fernando",
    edad: 38,
    sexo: "M",
    idCiudad: "C15",
    idEtapaVida: "EV4",
  },
];



const fields = ["idPaciente","nombre","edad","sexo","Ciudad_idCiudad","DesarrolloFisico_idEtapaVida"];

for (let index = 0; index < pacientes.length; index++) {
  insertData("paciente",fields, Object.values(pacientes[index]));

  console.log(Object.values(pacientes[index]))
  // console.log( estados.map( estado => Object.values(estado)))
}

// export {pacientes};